### PR TITLE
Update insuedthueringen.de.txt

### PR DESCRIPTION
**Pull request by HolgerAusB**
* show all Images of galleries [Wallabag+Fulltext-RSS]
* show article-image of short articles [Fulltext-RSS]
* known issue: does NOT show single article-image in short articles [Wallabag]

should close:
https://github.com/fivefilters/ftr-site-config/pull/1086

### CODE REVIEW

**Comment by HolgerAusB** [comment]
Don't know if this is the usual way to PR into a fork instead of main repo when suggesting alternative code. Be patient, please.

**Comment by Strubbl** [comment]
I just tested the config. For both example articles, the title image is missing in wallabag. I can see the image description below but not the image itself, see:

https://i.imgur.com/YJszmFn.png
https://i.imgur.com/PSqjMs2.png


> Don't know if this is the usual way to PR into a fork instead of main repo when suggesting alternative code. Be patient, please.

This should work. If i merge this here, it would show up in the PR of the ftr-site-config repo, where we already discussed.

**Comment by HolgerAusB** [comment]
Yes, because both test_url are short articles with that special article image. Try your example from the comments with that 1980er thing. You should get all 130 images with wallabag

**Comment by HolgerAusB** [comment]
I am afraid that Jérémy wait to see if we agree. The way I see it, my solution does not make anything worse in Wallabag. On the contrary, in-article images and galleries are taken over, only the top-images/title-images are missing, but this is also the case with your config, right? But my config helps Fulltext-RSS users, alle images are in here.  So you should decide, if you accept my PR or not and then write that clearly in the original PR, otherwise nothing will go further. I had hoped that you can also solve the problem with the title images, starting from my config.

**Comment by Strubbl** [comment]
> but this is also the case with your config, right?

Unfortunately not. My config loads the title image. Please compare https://i.imgur.com/xMSS8yq.png with your config https://i.imgur.com/YJszmFn.png. This is strange behaviour and i have no idea why.

If we could figure out how the title images also load, i can merge of course.

I would prefer to not load all images of a gallery, because loading 130 images is a lot. But this is not important to me. If that works, ok.

**Comment by Strubbl** [comment]
Ok, i think i fixed the title image problem.

**Pull request merged**
